name: poketter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  dio: ^5.4.3+1
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl:
  isar:
    hosted: https://pub.isar-community.dev
    version: ^4.0.3
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: ^4.0.3
  json_annotation: ^4.9.0
  logger: ^2.2.0
  path_provider: ^2.1.3
  responsive_framework: ^1.4.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  sign_in_button: ^3.2.0
  sign_in_with_apple: ^6.1.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.6.1
  json_serializable: ^6.8.0
  pedantic_mono: ^1.26.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - test/json/
