// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Um3rq0NV6gaUNjcMV-0qfMUanVos4UU',
    appId: '1:218586644870:web:b804e8a612f15a66d46c07',
    messagingSenderId: '218586644870',
    projectId: 'poketter-dev',
    authDomain: 'poketter-dev.firebaseapp.com',
    storageBucket: 'poketter-dev.appspot.com',
    measurementId: 'G-DSCM8WM210',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf5uUptP19zi7KaSN0-UTHV_-JIqI1Hf4',
    appId: '1:218586644870:android:9b944fe2964ae8a6d46c07',
    messagingSenderId: '218586644870',
    projectId: 'poketter-dev',
    storageBucket: 'poketter-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRdXLO-1mzq5ageJCgu1jTAu4PXMBg6wc',
    appId: '1:218586644870:ios:5bf493dbfeb7ccfbd46c07',
    messagingSenderId: '218586644870',
    projectId: 'poketter-dev',
    storageBucket: 'poketter-dev.appspot.com',
    iosBundleId: 'net.sukekyo.poketter.dev',
  );
}
