// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcfYq67PN1G25IxvDqc3fNQoF2ybHU8rI',
    appId: '1:119026552237:web:c7fef61f7ba0da4dafa524',
    messagingSenderId: '119026552237',
    projectId: 'poketter-prod',
    authDomain: 'poketter-prod.firebaseapp.com',
    storageBucket: 'poketter-prod.appspot.com',
    measurementId: 'G-S9QQ54NDS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApYxPaoGOtTYzFDh-vmTcF8QkXHnor7Hg',
    appId: '1:119026552237:android:66eed128375283ebafa524',
    messagingSenderId: '119026552237',
    projectId: 'poketter-prod',
    storageBucket: 'poketter-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC97XCQ7F2DhDPM9Fbzlk7s9rUBm3M20X4',
    appId: '1:119026552237:ios:6c5a66c3cc3cf0cfafa524',
    messagingSenderId: '119026552237',
    projectId: 'poketter-prod',
    storageBucket: 'poketter-prod.appspot.com',
    iosBundleId: 'net.sukekyo.poketter',
  );
}
